config/routes.rb
Rails.application.routes.draw do
  root 'index#index'

  get 'admin' => 'admin#enter'
  post 'admin' => 'admin#login'
  get 'admin/logout' => 'admin#logout'
  get 'admin/index' => 'admin#index'

  get 'about' => 'index#about'
  get 'corporate' => 'index#corporate'
  get 'sitemap' => 'index#sitemap'
  get 'privacy' => 'index#privacy'

  get 'contact' => 'inquiry#contact'

  get 'contents/hangouts' => 'contents#hangouts'
  get 'contents/hour_of_code' => 'contents#hour_of_code'
  get 'contents/scratch' => 'contents#scratch'
  get 'contents/codemonkey' => 'contents#codemonkey'
  get 'contents/ruby' => 'contents#ruby'
  get 'contents/ios' => 'contents#ios'
  get 'contents/android'  => 'contents#android'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  before_save :encrypt_password

  def encrypt_password
    self.password = encrypt(self.password)
  end

  def verify_password(password)
    begin
      password == decrypt(self.password)
    rescue
      return false
    end
  end

  # 暗号化
  def encrypt(password)
    crypt = ActiveSupport::MessageEncryptor.new(SECURE, CIPHER)
    crypt.encrypt_and_sign(password)
  end

  # 復号化
  def decrypt(password)
    crypt = ActiveSupport::MessageEncryptor.new(SECURE, CIPHER)
    crypt.decrypt_and_verify(password)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # gmail
  validates :gmail, :password, presence: true, uniqueness: { allow_blank: true }

before_save :encrypt_password

  def encrypt_password
    self.password = encrypt(self.password)
  end

  # 暗号化
  def encrypt(password)
    crypt = ActiveSupport::MessageEncryptor.new(SECURE, CIPHER)
    crypt.encrypt_and_sign(password)
  end

  # 復号化
  def decrypt(password)
    crypt = ActiveSupport::MessageEncryptor.new(SECURE, CIPHER)
    crypt.decrypt_and_verify(password)
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :login_check, except: [:enter, :login]

  def enter
  end

  def index
  end

  def login
    admin = Admin.first
    result = admin.nil? ? nil : admin.verify_password(params[:password])
    if result
      session['user'] = nil
      session['admin'] = admin
      redirect_to admin_index_path, notice: 'ブルーベリー・パイ管理画面です'
    else
      redirect_to admin_path, alert: '入力が間違っています'
    end
  end

  def logout
      session['admin'] = nil
      redirect_to root_path, notice: ''
  end

  private
  def login_check
    redirect_to admin_path, notice: 'ログインしてください' if session['admin'].nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def hangouts
  end

  def hour_of_code
  end

  def scratch
  end

  def ruby
  end

  def ios
  end

  def android
  end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    render :index
  end

  def about
    render :about
  end

  def corporate
    render :corporate
  end

  def sitemap
    render :sitemap
  end

  def privacy
    render :privacy
  end
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
	def contact
		@title = 'ブルーベリー・パイ：お問い合わせ'
		@contact = MailContact.new
		render :contact
	end

	def confirm_contact
		@title = 'ブルーベリー・パイ：お問い合わせ'
		@contact = MailContact.new
		@contact.update(contact_strong_params)
		if @contact.valid?
			render :confirm_contact
		else
			render :contact
		end
	end

	def post_contact
		@title = 'ブルーベリー・パイ：お問い合わせ'
		@contact = MailContact.new
		@contact.update(contact_strong_params)
		@contact.save

		InquiryMailer.confirm_contact(@contact).deliver
		InquiryMailer.contact(@contact).deliver

		render :post_contact
	end

private
  def mailmagazine_strong_params
    params.require(:mail_mailmagazine).permit(:email)
  end

  def contact_strong_params
    params.require(:mail_contact).permit(:corp_name, :name, :email, :detail)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/admin/enter.html.erb
  <div id="content" class="floatwrap">
  <div id="contentArea" class="floatwrap">

    <center>
      <%= form_tag admin_path, method: :post do %>
        <%= password_field_tag :password %>
        <%= submit_tag 'login' %>
      <% end %>
    </center>

  </div>
  </div>

app/views/contents/hour_of_code.html.erb
  <div id="content" class="floatwrap">
  <div id="contentArea" class="floatwrap">
    <%= render partial: 'layouts/side' %>
    <div id="main">
    <div class="main_header"></div>
      <p>
        <H2>Hour of Codeについて</H2>
        <div style="padding-left: 30px;">
          Hour of Codeはプログラミング初学者学習用のオンラインサービスです。<br/>
          作ったアプリはインターネットで公開することもできます。<br/>
        </div>
      </p>
      <p>
        <H2>Hour of Codeで作成した音楽再生アプリ</H2>
        <div style="padding-left: 30px;">
        （Androidでは再生できません）<br/>
        <center>
          <iframe width="352" height="620" style="border: 0px;" src="https://studio.code.org/projects/applab/wIHyrvrCNQYdfy-Ek_Psxg/embed"></iframe>
        </center>
        </div>
      </p>
    </div><!-- end of main_header -->
    </div><!-- end of main -->
  </div><!-- end of contentArea -->
  </div><!-- end of content -->

app/views/contents/scratch.html.erb
  <div id="content" class="floatwrap">
  <div id="contentArea" class="floatwrap">
    <%= render partial: 'layouts/side' %>
    <div id="main">
    <div class="main_header"></div>
      <p>
        <H2>Scratchについて</H2>
        <div style="padding-left: 30px;">
          Scratchはプログラミング初学者学習がビジュアルにコーディングするサービスです。<br/>
          オンラインサービスだけでなく、ローカルで開発可能なアプリケーション開発環境もあります。<br/>
          作ったアプリはインターネットで公開することもできます。<br/>
        </div>
      </p>
      <p>
        <H2>Scratchで開発したゲームアプリ</H2>
        <div style="padding-left: 30px;">
        <center>
            <iframe allowtransparency="true" width="485" height="402" src="//scratch.mit.edu/projects/embed/12278865/?autostart=false" frameborder="0" allowfullscreen></iframe>
        </center>
        </div>
      </p>
    </div><!-- end of main_header -->
    </div><!-- end of main -->
  </div><!-- end of contentArea -->
  </div><!-- end of content -->

app/views/index/about.html.erb
  <div id="content" class="floatwrap">
  <div id="contentArea" class="floatwrap">

    <%= render partial: 'layouts/side' %>

    <div id="main">
    <div class="main_header"></div>

      <%= yield %>

      <h2>ルームシェア東京とは？</h2>

      <p>ルームシェア東京は、ルームシェア＆シェアハウス物件専門の賃貸情報サイトです。<br>
      他のサイトにはない専門情報があることはもちろん、シェア生活に関する各種の情報提供やサポートなども行っています。</p>

      <div class="check_or">「もっと自由に、もっとワガママにシェア生活をしたい！」</div>

      <div class="check_or">「大好きな仲間たちと一緒に住める環境がほしい！」</div>

      <div class="check_or">「シェアなんだから、もっと費用を抑えたい！」</div>

      <div class="check_or">「自分達でカスタマイズしたり、インテリアをコーディネイトしたい！」</div>

      <div class="check_or">「住みたい場所にシェアハウスがない！」</div>

      <p>そんな想いを持った皆様の為に、ルームシェア可能な良質な物件や自由度の高いシェアハウスを厳選してお届けしてまいります！</p>

      <p>皆さんの快適なシェア生活を全力で応援いたしますので、是非、お気軽にご相談ください！！</p>

      <p>&nbsp;</p>

      <h2>物件のリクエストについて</h2>

      <p>当社で管理している物件は、サイトに掲載しているものが全てではありません。</p>

      <p>気に入った物件がなかった場合は、<a href="/inquiry/pr/">【物件リクエスト】</a>より、ご希望の内容をお知らせください。</p>

      <p>皆さんのこだわり物件探しをしっかりとサポートさせていただきます！</p>

    <div class="main_footer"></div>
    </div><!-- end div#main -->

  </div><!-- end div#contentArea -->
  </div><!-- end div#content -->

app/views/index/blog.html.erb
  <div id="content" class="floatwrap">
  <div id="contentArea" class="floatwrap">

    <%= render partial: 'layouts/side' %>

    <div id="main">
    <div class="main_header"></div>

      <%= yield %>

      <h2>ブログ</h2>

      <p>ブログの紹介</p>

      <p>&nbsp;</p>

    <div class="main_footer"></div>
    </div><!-- end div#main -->

  </div><!-- end div#contentArea -->
  </div><!-- end div#content -->

app/views/index/corporate.html.erb
  <div id="content" class="floatwrap">
  <div id="contentArea" class="floatwrap">

    <%= render partial: 'layouts/side' %>

    <div id="main">
    <div class="main_header"></div>

      <%= yield %>

      <h2>運営会社</h2>

      <table border="0" cellpadding="0" cellspacing="0" class="corp">

        <tr>
          <th>運営会社</th>
          <td>TEAMスキマジャパン</td>
        </tr>

        <tr>
          <th>協力会社</th>
          <td>株式会社東京みらい不動産</td>
        </tr>

        <tr>
          <th>宅建免許番号</th>
          <td>東京都知事免許（１）第９４５１５号</td>
        </tr>

        <tr>
          <th>所属団体</th>
          <td>
            (公社)東京都宅地建物取引業協会会員<br>
            (公社)首都圏不動産公正取引協議会加盟
          </td>
        </tr>

        <tr>
          <th>保証協会</th>
          <td>(公社)全国宅地建物取引業保証協会</td>
        </tr>

        <tr>
          <th>TEL</th>
          <td>070-5517-7096</td>
        </tr>

        <tr>
          <th>FAX</th>
          <td>03-6740-6436</td>
        </tr>

        <tr>
          <th>MAIL</th>
          <td><a href="mailto:info@sukimajapan.com">info@sukimajapan.com</a></td>
        </tr>

        <tr>
          <th>住所</th>
          <td>東京都杉並区阿佐谷南1-8-3-1Ａ</td>
        </tr>

        <tr>
          <th>営業時間</th>
          <td>10:00～20:00</td>
        </tr>

        <tr>
          <th>定休日</th>
          <td>年中無休（年末年始除く）</td>
        </tr>

      </table>

      <p>&nbsp;</p>


    <div class="main_footer"></div>
    </div><!-- end div#main -->

  </div><!-- end div#contentArea -->
  </div><!-- end div#content -->

app/views/index/index.html.erb
  <div id="content" class="floatwrap">
  <div id="contentArea" class="floatwrap">

    <%= render partial: 'layouts/side' %>

    <div id="main">
    <div class="main_header"></div>

      <%= yield %>

      <div class="floatwrap">

      <div class="main_left">
      <h6><%= image_tag("main_tit_04.jpg", alt: "シェア生活・口コミ情報", width: "356", height: "46") %></h6>
        ・<%= link_to 'Googleハングアウトについて', contents_hangouts_path %><br/>
        ・<%= link_to 'Hour of Codeについて', contents_hour_of_code_path %><br/>
        ・<%= link_to 'Scratchについて', contents_scratch_path %><br/>
        ・<%= link_to 'Code Monkeyについて', contents_codemonkey_path %><br/>
        ・<%= link_to 'Rubyについて', contents_ruby_path %><br/>
        ・<%= link_to 'iOS開発について', contents_ios_path %><br/>
        ・<%= link_to 'Android開発について', contents_android_path %><br/>
      </div><!-- end div.main_right -->

      <div class="main_right">
      <h6><%= image_tag("main_tit_03.jpg", alt: "新着ブログ記事紹介", width: "356", height: "46") %></h6>
        <p>
        ・<%= link_to 'ブログ「たのしいプログラミング」', 'http://ameblo.jp/hardcastle/', target: '_blank' %><br/>
        ・<%= link_to 'チラシ', '/download/Blueberry-Piチラシ.pdf', target: '_blank' %><br/>
        ・<%= link_to 'Hour of Code', 'https://code.org/', target: '_blank' %><br/>
        ・<%= link_to 'SCRATCH', 'https://scratch.mit.edu/', target: '_blank' %><br/>
        ・<%= link_to 'Code Monkey', 'https://codemonkey.jp/' %><br/>
        </p>
        <p>
        ・<%= link_to 'オススメHTML5、CSS3学習サイト', 'http://honttoni.blog74.fc2.com/', target: '_blank' %><br/>
        ・<%= link_to 'オススメRuby学習サービス15選', 'https://techacademy.jp/magazine/6154', target: '_blank' %><br/>
        ・<%= link_to 'Swift/iOS入門に最適なチュートリアルサイト10個', 'https://mayonez.jp/1526', target: '_blank' %><br/>
        ・<%= link_to 'Androidアプリ開発入門チュートリアルサイトまとめ', 'https://mayonez.jp/1567', target: '_blank' %><br/>
        </p>
      </div><!-- end div.main_left -->

      </div><!-- end div.floatwrap -->

      <%= render partial: 'layouts/news' %>

    <div class="main_footer"></div>
    </div><!-- end div#main -->

  </div><!-- end div#contentArea -->
  </div><!-- end div#content -->

app/views/index/link.html.erb
  <div id="content" class="floatwrap">
  <div id="contentArea" class="floatwrap">

    <%= render partial: 'layouts/side' %>

    <div id="main">
    <div class="main_header"></div>

      <%= yield %>

      <h2>リンク集</h2>

      <p>リンク集</p>

      <p>&nbsp;</p>

    <div class="main_footer"></div>
    </div><!-- end div#main -->

  </div><!-- end div#contentArea -->
  </div><!-- end div#content -->

app/views/index/privacy.html.erb
  <div id="content" class="floatwrap">
  <div id="contentArea" class="floatwrap">

    <%= render partial: 'layouts/side' %>

    <div id="main">
    <div class="main_header"></div>

      <%= yield %>

      <h2>プライバシーポリシー</h2>

      <h4>第１条（全般）</h4>

      <p>ルームシェア東京（以下「本サイト」という）を運営するスキマジャパン（以下「管理人」という）は，本サイトの利用者（以下「ユーザー」という）のプライバシーを尊重し，ユーザーの個人情報の管理に細心の注意を払うものとします。　</p>
      <p>管理人は，責任をもってユーザーの個人情報を保護するための方針を以下のとおり定め，施策の実施・維持，それらの継続的な改善を行います。</p>
      <p>管理人は，個人情報保護に関する法令及びその他の規範を遵守します。</p>

      <h4>第２条（個人情報）</h4>

      <p>本プライバシーポリシーにおいて「個人情報」とは，個人情報保護法にいう，生存する個人に関する情報であって，当該情報に含まれる氏名，住所，電話番号，メールアドレス及びその他の記述等により特定の個人を識別することができるもの（他の情報と容易に照合することができ，それにより特定の個人を識別することができることとなるものを含む）をいいます。</p>

      <h4>第３条（個人情報の収集）</h4>

      <p>管理人は，個人情報の入手を適法かつ公正な手段によって行うものとし，ユーザーの意思に反する不正な入手を行わないものとします。</p>
      <p>管理人は，個人情報を収集する場合，その利用目的をあらかじめ通知又は公表するものとします。</p>

      <h4>第４条（管理人によるクッキー等の使用について）</h4>

      <p>管理人は，クッキー及びIPアドレス等から履歴情報及びその他のユーザーのプライバシーに係る情報を収集する場合があります。</p>
      <p>ユーザーは，ブラウザの設定でクッキー等を無効にすることにより，管理人のクッキー等の使用を拒否することができます。</p>
      <p>ただし，クッキー等を無効にした場合，同ユーザーは，各サービスの利用状況を確認する等の際に，何らかの不具合が生じる可能性があることに注意する必要があります。</p>

      <h4>第５条（個人情報の利用目的）</h4>

      <p>管理人は，ユーザーから収集した個人情報等を以下の目的のために使用するものとします。</p>
      <p>(1)　不動産の仲介・管理、売買、その他付帯業務</p>
      <p>(2)　前項の利用目的の達成に必要な範囲での、個人情報の第三者への提供</p>
      <p>(3)　本サイトのユーザー向けサービスを提供・管理するため</p>
      <p>(4)　お問い合わせ・ご相談に対する回答・返信をする場合。</p>
      <p>(5)　ユーザーに対して管理人のサービスに対する意見，感想の提供を求める場合。</p>
      <p>(6)　本サイト内各規約等に違反する行為又はその恐れのある行為を行ったユーザーに対して注意又は警告を行う場合。</p>

      <h4>第６条（個人情報の第三者提供）</h4>

      <p>管理人は，収集した個人情報等を個人情報保護法及び行政書士法に基づき第三者に対して開示又は提供しないものとします。<br>ただし，以下の各号に該当する場合は，この限りではありません。</p>
      <p>(1)　ユーザーがサイト上の機能を用いて自ら情報公開をした場合</p>
      <p>(2)　お客様から第三者への情報開示について予め同意を頂いた場合</p>
      <p>(3)　人の生命，身体又は財産の保護のために必要がある場合であって，本人の同意を得ることが困難である場合。</p>
      <p>(4)　警察，検察，裁判所，消費者センター等公的機関等によって開示を求められた場合。</p>
      <p>(5)　業務を円滑に進める等の理由で、外部業者に取り扱いを委託する場合</p>
      <p>(6)　法令により開示が認められている場合。</p>
      <p>(7)　法令により開示を求められた場合。</p>

      <h4>第７条（個人情報等の管理）</h4>

      <p>管理人は，個人情報保護法及び行政書士法に基づき個人情報等を厳重に管理し機密保持に努めるものとします。<br>ただし，管理人は，情報の漏洩，消失，他者による改ざん等が完全に防止されることについてのユーザーに対する保証を一切行わないものとします。</p>

      <h4>第８条（個人情報等の最新性・正確性の維持）</h4>

      <p>管理人は，利用目的の達成に必要な範囲内において，ユーザーの個人情報等を正確かつ最新の内容に保つよう努めるものとします。</p>

      <h4>第９条（ユーザーによる照会等）</h4>

      <p>管理人は，ユーザーより当該ユーザーの個人情報の照会・訂正・追加・削除・利用の停止又は消去を求められた場合，本人確認を行うものとします。　なお，管理人は，ユーザー本人による照会等であると管理人が判断した場合，合理的な期間内に同照会等に対応するものとします。</p>

      <h4>第１０条（利用目的等の変更）</h4>

      <p>個人情報の利用目的及び管理方法等の変更等，本プライバシーポリシーの変更は，管理人が変更後のプライバシーポリシーを本サイト上に掲載した時点で効力を生じるものとします。</p>

      <h4>第１１条（免責）</h4>

      <p>管理人は，第三者によるユーザーの個人情報の取得があった場合でも，以下に該当する場合，一切責任を負いません。</p>
      <p>(1)　ユーザーが本サイトの機能又は別の手段を用いて第三者に個人情報を明らかにした場合。</p>
      <p>(2)　ユーザーが同第三者の個人情報の取得について追認した場合。</p>
      <p>(3)　本サイト内のリンク先である他サイトから個人情報を取得した場合。　</p>
      <p>管理人は，本サイト上のリンク先のウェブサイトにおけるプライバシー保護に関して一切責任を負いません。リンク先への訪問等は，ユーザー自身の責任にて行うものとします。</p>

      <p>&nbsp;</p>

    <div class="main_footer"></div>
    </div><!-- end div#main -->

  </div><!-- end div#contentArea -->
  </div><!-- end div#content -->

app/views/index/sitemap.html.erb
  <div id="content" class="floatwrap">
  <div id="contentArea" class="floatwrap">

    <%= render partial: 'layouts/side' %>

    <div id="main">
    <div class="main_header"></div>

      <%= yield %>

      <h2>サイトマップ</h2>

      <h4>制作済み</h4>
      <ul class="sitemap">
        <li>・[form]<%= link_to('空き室を貸したい',controller: :inquiry, action: :vacanthouse) %></li>
        <li>・[form]<%= link_to('口コミ情報求む', controller: :inquiry, action: :review) %></li>
        <li>・<%= link_to 'ルームシェア東京とは', "about" %></li>
        <li>・<%= link_to '運営会社', "corporate" %></li>
        <li>・<%= link_to 'サイトマップ', "sitemap" %></li>
        <li>・<%= link_to 'リンク集', "link" %></li>
        <li>・<%= link_to 'プライバシーポリシー', "privacy" %></li>
        <li>・<%= link_to '路線・駅名で探す', "line" %></li>
        <li>・<%= link_to 'エリアで探す', "area" %></li>
        <li>・<%= link_to 'ブログ', "blog" %></li>
        <li>・<%= link_to '口コミ情報', "review" %></li>
        <li>・<%= link_to '間取りで探す', "madori" %></li>
        <li>・<%= link_to '条件で探す', "conditions" %></li>
        <li>・<%= link_to 'アバランチ阿佐ヶ谷', "/room/abaranchiasagaya" %></li>
        <li>・<%= link_to 'WHITE HOUSE 桜台', "/room/whitehousesakuradai" %></li>
      </ul>

      <p>&nbsp;</p>

      <h4>未対応</h4>
      <ul class="sitemap">
        <li>[form]MAIL MAGAZINE</li>
        <li>[form]オーナー様不動産会社様へ</li>
        <li>[form]こんな物件を探してほしい</li>
        <li>[form]お問い合わせ</li>
      </ul>

      <p>&nbsp;</p>


    <div class="main_footer"></div>
    </div><!-- end div#main -->

  </div><!-- end div#contentArea -->
  </div><!-- end div#content -->

app/views/inquiry/confirm_contact.html.erb
<div id="content" class="floatwrap">
<div id="contentArea" class="floatwrap">

  <%= render partial: 'layouts/side' %>

  <div id="main">
  <div class="main_header"></div>

    <article id="post-8" class="post-8 page type-page status-publish hentry box-middle post">


    <h2>お問い合わせ</h2>


    <p><a href="/privacy/">プライバシーポリシー</a>をご確認いただき、ご同意のうえご送信ください。</p>
    <h6 class="clear"><%= image_tag "spacer.gif", alt: "space", height: "20" %></h6>


    <%= form_for @contact, url: {action: :post_contact} do |f| %>

      <div id="input-hidden"><!-- フォーム用 hidden データ -->
        <%= f.hidden_field :corp_name %>
        <%= f.hidden_field :name %>
        <%= f.hidden_field :email %>
        <%= f.hidden_field :detail %>
      </div>

      <label for="contact_1">

      <table border="0" cellpadding="0" cellspacing="0" class="form">

        <tr>
          <th>件名<span class="red">【必須】</span></th>
          <td>
            <%= @contact.corp_name %>
          </td>
        </tr>
        <tr>

        </tr>
        <tr>
          <th>お名前<span class="red">【必須】</span></th>
          <td>
            <%= @contact.name %>
          </td>
        </tr>

        <tr>
          <th>メールアドレス<span class="red">【必須】</span></th>
          <td>
            <%= @contact.email %>
          </td>
        </tr>

        <tr>
          <th>コメント記入欄<span class="red">【必須】</span></th>
          <td>
            <%= @contact.detail %>
          </td>
        </tr>
      </table>

      <div class="form_btn">
        <input type="image" src="/assets/submit_btn.jpg" onMouseOver="this.src='/assets/submit_btn_o.jpg'" onMouseOut="this.src='/assets/submit_btn.jpg'" class="submit">
      </div>

    <% end %>

    </article>

  <div class="main_footer"></div>
  </div><!-- end div#main -->

</div><!-- end div#contentArea -->
</div><!-- end div#content -->

app/views/inquiry/confirm_mailmagazine.html.erb
<div id="content" class="floatwrap">
<div id="contentArea" class="floatwrap">

  <%= render partial: 'layouts/side' %>

  <div id="main">
  <div class="main_header"></div>

    <article id="post-8" class="post-8 page type-page status-publish hentry box-middle post">


    <h2>ルームシェア東京　無料メールマガジン</h2>

    <%= form_for @mailmagazine, url: {action: :post_mailmagazine} do |f| %>

      <div id="input-hidden"><!-- フォーム用 hidden データ -->
        <%= f.hidden_field :email %>
      </div>

      <table border="0" cellpadding="0" cellspacing="0" class="form">

        <tr>
          <th>メールアドレス<span class="red">【必須】</span></th>
          <td>
            <%= @mailmagazine.email %>
          </td>
        </tr>

      </table>

      <div class="form_btn">
        <input type="image" src="/assets/submit_btn.jpg" onMouseOver="this.src='/assets/submit_btn_o.jpg'" onMouseOut="this.src='/assets/submit_btn.jpg'" class="submit">
      </div>

    <% end %>

    </article>

  <div class="main_footer"></div>
  </div><!-- end div#main -->

</div><!-- end div#contentArea -->
</div><!-- end div#content -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title><%= @title.nil? ? 'ブルーベリー・パイ' : @title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>
</head>
<body>
<a name="top" id="top"></a>

  <div id="header">
  <div id="headerArea">
    <div class="header_txt"><h1>オンラインプログラミング教室　ブルーベリー・パイ</h1></div>
    <div class="header_logo"><%= link_to image_tag("site-logo.gif", alt: "ブルーベリー・パイ", width: "271", height: "50"), 'http://www.blueberry-pi.xyz' %></a></div>

    <div id="gnavi">
      <ul id="globalnavi">
      <li><%= link_to(image_tag("gnavi_01.jpg", alt: "TOP", width: "156", height: "43"), controller: :index, action: :index) %></li>
      <li><%= link_to(image_tag("gnavi_02.jpg", alt: "About Site", width: "156", height: "43"), about_path) %></li>
      </ul>
    </div>
    <!-- end div#gnavi -->

  </div><!-- end div#headerArea -->
  </div><!-- end div#header -->

  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
  <%= yield %>

  <div id="footer">
  <div id="footerArea" class="floatwrap">

    <div class="footer_logo">
    <div class="footer_elogo">
    <h6><%= link_to image_tag("footer_elogo.jpg", alt: "ブルーベリー・パイロゴ", width: "72", height: "66"), "http://www.sukimajapan.com", target: "_blank" %></a></h6>
    </div>
    <div class="footer_corp">
    <h6><%= image_tag("footer_logo.jpg", alt: "090-8508-8128", width: "150", height: "20") %></h6>
      <p>〒215-0018<br>
        神奈川県川崎市麻生区王禅寺東4-20-1</p>
    </div>
    </div>

    <div class="footer_navi">
      <ul>
      <li>・<%= link_to 'ブルーベリー・パイとは', about_path %></li>
      <li>・<%= link_to '運営会社', corporate_path %></li>
      <li>・<%= link_to 'サイトマップ', sitemap_path %></li>
      <li>・<%= link_to 'プライバシーポリシー', privacy_path %></li>
      <li>・<%= link_to 'お問い合わせ', contact_path %></li>
      </ul>
    </div>

  <div class="footer_copy">Copyright (C) 2016 <%= link_to 'ブルーベリー・パイ', "http://www.blueberry-pi.xyz" %> All Rights Reserved.</div>

  </div><!-- end div#footerArea -->
  </div><!-- end div#footer -->

<!-- start google-analytics -->

<!-- end google-analytics -->
</body>
</html>